[project]
name = "bw"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "lmdb>=1.7.5",
    "openai>=2.9.0",
    "pdfminer-six>=20251107",
    "pyyaml>=6.0.3",
    "surrealdb>=1.0.7",
    "watchdog>=6.0.0",
]
